### PR TITLE
Artik10 add udlfb

### PR DESCRIPTION
**Pull request by floion**
@agherzan @telphan @petrosagg

### CODE REVIEW

**Comment by lifeeth** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-os/resin-artik/3)_

**Comment by lifeeth** [comment]
LGTM

**Comment by agherzan** [comment]
LGTM

**Comment by agherzan** [comment]
Closing as we are using mipi display instead.

**Pull request closed without merging**
